const COLOR_CHARCOAL = '#36454F';
const COLOR_BEIGE = '#F0F2E7';
const COLOR_IVORY = '#EEEEEE';
const COLOR_BROWN = '#CCA78A';
const COLOR_GREEN = '#BDF0D6';
const COLOR_BLUE = '#0058C1';
const COLOR_CYAN = '#75CEE5';
const COLOR_PURPLE = '#8275E5';
const COLOR_RED = '#CD000E';
const COLOR_PINK = '#E575A5';
const COLOR_ORANGE = '#F27000';
const COLOR_YELLOW = '#f1b312';

const COLOR_BACKGROUND = COLOR_IVORY;
const COLOR_BODY_TEXT = COLOR_CHARCOAL;
const COLOR_LINK_TEXT = COLOR_PURPLE;

export {
  COLOR_CHARCOAL,
  COLOR_BEIGE,
  COLOR_IVORY,
  COLOR_BROWN,
  COLOR_GREEN,
  COLOR_BLUE,
  COLOR_CYAN,
  COLOR_PURPLE,
  COLOR_RED,
  COLOR_PINK,
  COLOR_ORANGE,
  COLOR_YELLOW,
  COLOR_BACKGROUND,
  COLOR_BODY_TEXT,
  COLOR_LINK_TEXT,
};
